title: Sofa Mouse
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 1
favicon: null
name: sofamouse
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 1
  saturation: 0.4085106
  rhythmicContrast: 0.7702128
  brandColors:
    - '#D6C6A3'
    - '#16171F'
    - '#C53980'
    - '#77E1B3'
    - '#4B535C'
typography_spectrum: 0.3368
