name: sofamouse
favicon: null
layout_spectrum: 0.59726
typography_spectrum: 0.3368
title: Sofa Mouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#525e6a'
    - '#212e37'
    - '#374756'
    - '#747f47'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
