name: sofamouse
favicon: null
layout_spectrum: 0.9878443912602961
typography_spectrum: 0.9150502060074359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7842209292575717
  lightness: 0.12821896420791745
  saturation: 0.8966692425310612
  rhythmicContrast: 0.840616846922785
purpose: []
